# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 22:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cinemadatabase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='actor',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='actor',
            name='bio',
            field=models.CharField(default='placeholder bio', max_length=2000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='film',
            name='description',
            field=models.CharField(default='placeholder description', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='discussion',
            name='id_film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinemadatabase.Film'),
        ),
        migrations.AddField(
            model_name='discussion',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='id_discussion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cinemadatabase.Discussion'),
        ),
        migrations.AddField(
            model_name='comment',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actor',
            name='image',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='cinemadatabase.Url'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='film',
            name='category',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='cinemadatabase.Category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='film',
            name='image',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='cinemadatabase.Url'),
            preserve_default=False,
        ),
    ]
