# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-12 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemadatabase', '0003_auto_20180112_2252'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='title',
            field=models.CharField(default='placeholder title', max_length=100),
            preserve_default=False,
        ),
    ]
