# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-13 07:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinemadatabase', '0004_discussion_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='image',
            field=models.FileField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='film',
            name='image',
            field=models.FileField(upload_to='images'),
        ),
        migrations.DeleteModel(
            name='Url',
        ),
    ]
